// Plan features for SellerCFO
// Auto-generated by Jarvis Pipeline

export const PLAN_FEATURES = {
  essential: {
    name: "Essential",
    price: 299,
    features: [
    "Core KPI Dashboard",
    "Shopify + Amazon Integration",
    "QuickBooks Sync",
    "Unit Economics Tracking",
    "30-day Data History",
    "Email Support"
    ],
  },
  professional: {
    name: "Professional",
    price: 599,
    features: [
    "Essential +",
    "All Marketing Integrations",
    "Inventory Forecasting",
    "Custom Reports",
    "API Access",
    "Unlimited History",
    "Priority Support"
    ],
  },
  enterprise: {
    name: "Enterprise",
    price: 1299,
    features: [
    "Professional +",
    "Multi-store Support",
    "Custom Integrations",
    "White-label Options",
    "Dedicated Account Manager",
    "Advanced AI Insights"
    ],
  },
} as const;

export type PlanTier = keyof typeof PLAN_FEATURES;
